#!/usr/bin/python

# Copyright (C) 2011 by Ralph Bearpark.
# Contact: <http://www.bearpark.ch/who/ralph/>.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import math
import sys
import cgi
import numnames

print 'Content-type: text/html\n\n'
form = cgi.FieldStorage()   # FieldStorage object to
                            # hold the form data

number=None
# check whether a field called "number" was used...
# it might be used multiple times (so sep w/ commas)
if form.has_key('number'):
    number = form["number"].value
n=numnames.numnames()
words = n.checkandtranslate(number)

print """<html>
<head>
<title>Number to Words</title>
</head>
<body style="font-family:verdana">
<h1>Display a Number in Words</h1>
<form name="input" action="numnames" method="get">
 <table>
 <tr>
  <td><b>Number:</b></td>
  <td><input type="text" name="number" value="%s" />
  <input type="submit" value="Submit" /></td>
 </tr>
 <tr>
  <td><b>Words:</b></td>
  <td>%s</td>
 </tr>
 </table> 
</form>
<p style="font-size:50%%">Brought to you by <a href="http://www.bearpark.ch/who/ralph">Ralph Bearpark</a>.</p>
</body>
</html>
""" % (number, words)

